[language-server]
fish-lsp = { command = "fish-lsp", args = [
  "start",
], environment = { fish_lsp_show_client_popups = "false" } }

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "fish"
language-servers = ["fish-lsp"]
auto-format = true

[[language]]
name = "nix"
formatter = { command = "nixfmt" }
auto-format = true

[[language]]
name = "toml"
auto-format = true
