[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
comment-token = "#"
language-servers = ["nil"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = "nixfmt" }

[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml"]
comment-token = "#"
language-servers = ["taplo"]
indent = { tab-width = 2, unit = "  " }
