#! /usr/bin/env bash

readonly term="alacritty"
readonly menu="kickoff"
readonly fm="lf"

readonly mod="Super"
readonly move_mod="$mod+Shift"

# apps
riverctl map normal $mod Return spawn $term
riverctl map normal $mod S spawn $menu
riverctl map normal $mod E spawn "$term -e $fm"

# window
riverctl map normal $mod Q close
riverctl map normal $mod Space toggle-float
riverctl map normal $mod F toggle-fullscreen

riverctl map normal $mod J focus-view up
riverctl map normal $mod K focus-view down
riverctl map normal $mod H focus-view left
riverctl map normal $mod L focus-view right

riverctl map normal $move_mod J swap up
riverctl map normal $move_mod K swap down
riverctl map normal $move_mod H swap left
riverctl map normal $move_mod L swap right

# modes
readonly mode_mod="$mod+Alt"
declare -A modes=(power P)
for mode in ${!modes[*]}; do
    key=${modes[$mode]}
    riverctl declare-mode $mode
    riverctl map normal $mode_mod $key enter-mode $mode
    riverctl map $mode None Escape enter-mode normal
done

riverctl map power None P spawn poweroff
riverctl map power None R spawn reboot
riverctl map power None S spawn "riverctl enter-mode normal && systemctl suspend"
riverctl map power None Q exit

# universal
readonly volume_step=0.02
for mode in normal ${!modes[*]}; do
    riverctl map $mode None XF86AudioMute spawn "wpctl set-mute @DEFAULT_SINK@ toggle"
    riverctl map $mode None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_SINK@ $volume_step-"
    riverctl map $mode None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_SINK@ $volume_step+"
done

# mouse
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# tags
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Control $i set-view-tags $tags
    riverctl map normal $mod+Shift $i spawn "riverctl set-view-tags $tags && riverctl set-focused-tags $tags"
done
