#! /usr/bin/env bash

readonly term="wezterm"
readonly menu="kickoff --from-file $HOME/.config/kickoff/app-menu"
readonly explorer="$term -e yazi"

readonly mod="Super"
readonly move_mod="$mod+Shift"

# apps
riverctl map normal $mod Return spawn $term
riverctl map normal $mod S spawn "$menu"
riverctl map normal $mod E spawn "$explorer"

# window
riverctl map normal $mod Q close
riverctl map normal $mod Space toggle-float
riverctl map normal $mod F toggle-fullscreen

riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal $move_mod J swap next
riverctl map normal $move_mod K swap previous
riverctl map normal $move_mod H send-layout-cmd rivertile "main-count -1"
riverctl map normal $move_mod L send-layout-cmd rivertile "main-count +1"

switch_mode="switch-mode"
riverctl declare-mode $switch_mode
riverctl map normal $mod Escape enter-mode $switch_mode
riverctl map $switch_mode None Escape enter-mode normal

# modes
declare -A modes=(power P)
for mode in ${!modes[*]}; do
    key=${modes[$mode]}
    riverctl declare-mode $mode
    riverctl map $switch_mode None $key enter-mode $mode
    riverctl map $mode None Escape enter-mode normal
done

riverctl map $switch_mode None Q exit

riverctl map power None P spawn poweroff
riverctl map power None R spawn reboot
riverctl map power None S spawn "riverctl enter-mode normal && systemctl suspend"

# universal
readonly volume_step=0.02
for mode in normal ${!modes[*]}; do
    riverctl map $mode None XF86AudioMute spawn "wpctl set-mute @DEFAULT_SINK@ toggle"
    riverctl map $mode None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_SINK@ $volume_step-"
    riverctl map $mode None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_SINK@ $volume_step+"
done

# mouse
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# tags
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Control $i set-view-tags $tags
    riverctl map normal $mod+Shift $i spawn "riverctl set-view-tags $tags && riverctl set-focused-tags $tags"
done
