#!/usr/bin/env bash

set -e

bin_dir=/run/current-system/sw/bin/
name=$1

if [[ $(nixos-container list | grep -E "^$name$") == "" ]]; then
  sudo ${bin_dir}extra-container create -s "$HOME/.local/share/nixos-container/$name".nix
else
  if [[ "down" == $(nixos-container status "$name") ]]; then
    sudo ${bin_dir}nixos-container start "$name"
  fi
fi

if [[ -n $2 ]]; then
  sudo ${bin_dir}machinectl shell container@"$name" /usr/bin/env bash --login -c "$2"
fi
