#!/usr/bin/env bash

set -e

full_path=/run/current-system/sw/bin/
name=$1
session_dir="/run/nixos-containers/$name"
user=$USER

create_cuntime_dir() {
  if [[ ! -d "$session_dir" ]]; then
    sudo mkdir -p "$session_dir"
    sudo chown $user "$session_dir"
  fi
}

if [[ $(nixos-container list | grep -E "^$name$") == "" ]]; then
  create_cuntime_dir
  sudo ${full_path}extra-container create -s "$HOME/.config/nixos-container/$name".nix
else
  if [[ "down" == $(nixos-container status "$name") ]]; then
    create_cuntime_dir
    sudo ${full_path}nixos-container start "$name"
  fi
fi

if [[ -n $2 ]]; then
  sudo ${full_path}machinectl shell container@"$name" /usr/bin/env bash --login -c "$2"
fi
