# Kickoff default config

# Characters shown in front of the query.
prompt = '>  '

# space between window border and the content in pixel
padding = 160

fonts = [
    'CaskaydiaMono NF',
    'Noto Sans Mono',
] # list of otf or ttf fonts. later elements work as fallback
font_size = 32.0

[history]
decrease_interval = 48 # interval to decrease the number of launches in hours

[colors]
# color format: rgb or rgba, if transparency is desired
background = '#24273aee'
prompt = '#ed8796'
text = '#cad3f5'          # for search results
text_query = '#cad3f5'    # for the search query
text_selected = '#eed49f' # for the currently selected result

[keybindings]
# keybindings syntax: ctrl/shift/alt/logo as modifiers and a key joined by '+' signs
# A list of available keys can be found here: https://docs.rs/crate/x11-keysymdef/0.2.0/source/src/keysym.json
paste = ["ctrl+v"]
execute = ["Return"]
delete = ["BackSpace"]
delete_word = ["ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
