[mouse]
bindings = [{ mouse = "Right", action = "ExpandSelection" }]

[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "Up", mods = "Control", mode = "~Alt", action = "ScrollLineUp" },
  { key = "Down", mods = "Control", mode = "~Alt", action = "ScrollLineDown" },
  { key = "PageUp", mods = "Control", mode = "~Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Control", mode = "~Alt", action = "ScrollPageDown" },
  { key = "Home", mods = "Control", mode = "~Alt", action = "ScrollToTop" },
  { key = "End", mods = "Control", mode = "~Alt", action = "ScrollToBottom" },
  { key = "=", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "0", mods = "Control", action = "ResetFontSize" },
  { key = "Escape", action = "ClearLogNotice" },
  { key = "Escape", action = "ClearSelection" },
  { key = "Escape", action = "ReceiveChar" },

  # search
  { key = "F", mods = "Control|Shift", mode = "~Search|~Alt", action = "SearchForward" },
  { key = "F", mods = "Control|Shift", mode = "Search", action = "SearchCancel" },
  { key = "Escape", mode = "Search", action = "SearchCancel" },
  { key = "Enter", mode = "Search", action = "SearchConfirm" },
  { key = "Backspace", mods = "Alt", mode = "Search", action = "SearchDeleteWord" },
  { key = "ArrowLeft", mode = "Search", action = "SearchFocusPrevious" },
  { key = "ArrowRight", mode = "Search", action = "SearchFocusNext" },
  { key = "ArrowUp", mode = "Search", action = "SearchHistoryPrevious" },
  { key = "ArrowDown", mode = "Search", action = "SearchHistoryNext" },
]
