[keyboard]
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "L", mods = "Control", chars = "\u000c" },
  { key = "PageUp", mode = "~Alt", action = "ScrollPageUp" },
  { key = "PageDown", mode = "~Alt", action = "ScrollPageDown" },
  { key = "=", mods = "Control", action = "IncreaseFontSize" },
  { key = "-", mods = "Control", action = "DecreaseFontSize" },
  { key = "0", mods = "Control", action = "ResetFontSize" },

  # search
  { key = "F", mods = "Control|Shift", mode = "~Search|~Alt", action = "SearchForward" },
  { key = "F", mods = "Control|Shift", mode = "Search", action = "SearchCancel" },
  { key = "Escape", mode = "Search", action = "SearchCancel" },
  { key = "Enter", mode = "Search", action = "SearchConfirm" },
  { key = "Backspace", mods = "Alt", mode = "Search", action = "SearchDeleteWord" },
  { key = "ArrowLeft", mode = "Search", action = "SearchFocusPrevious" },
  { key = "ArrowRight", mode = "Search", action = "SearchFocusNext" },
  { key = "ArrowUp", mode = "Search", action = "SearchHistoryPrevious" },
  { key = "ArrowDown", mode = "Search", action = "SearchHistoryNext" },
]
